### ISSUE TITLE
LRU is not thread-safe

### ISSUE THREAD

**Issue by andresriancho** [deterministic-arts/DartsPyLRU#2]
Hi there, I'm the project leader for [w3af](https://github.com/andresriancho/w3af/), and we just started to use darts' LRU in our code.

One of the places where we use the LRU is [here](https://github.com/andresriancho/w3af/blob/293670749e767e90536a1a321f5891b8e2a080dd/w3af/core/controllers/core_helpers/fingerprint_404.py#L34) and because of multiple threads we're using `SynchronizedLRUDict`. The issue seems to be that the LRU is not actually thread-safe, as seen [here](https://github.com/andresriancho/w3af/issues/3621)

Any ideas on what could be wrong?

**Comment by andresriancho** [comment]
[This is how we use the LRU](https://github.com/andresriancho/w3af/blob/293670749e767e90536a1a321f5891b8e2a080dd/w3af/core/controllers/core_helpers/fingerprint_404.py#L50):

``` python
def lru_404_cache(wrapped_method):

    @wraps(wrapped_method)
    def inner(self, http_response):
        path = http_response.get_uri()

        try:
            return self.is_404_LRU[path]
        except KeyError:
            result = wrapped_method(self, http_response)
            self.is_404_LRU[path] = result
            return result

    return inner
```

**Comment by andresriancho** [comment]
[Our users use the `0.5` release of this module](https://github.com/andresriancho/w3af/blob/master/w3af/core/controllers/dependency_check/requirements.py#L45)

**Comment by deterministic-arts** [comment]
Unfortunately, there is not really much in the stacktrace, from which I could start searching for the problem. A few questions: 
- What kind of keys do you use the LRU dictionary with? Plain strings? Custom objects?
- How's the LRU dict created? Are you passing (2nd arg.) an explicit lock into the constructor?

(This is just a hunch from your work-around; I haven't read more than the snippet above of your code): Please note, that neither `LRUDict` nor `SychronizedLRUDict` are re-entrant, i.e., if the `__eq__` (or `__hash__`) method of a key does access the LRU dictionary in question, then all bets are off as to what the result might be. This is somewhat by design (it makes the implementation simple).

**Comment by deterministic-arts** [comment]
Just skimming through your code... The `URL` class seems to have mutable state and the concept of equality for this class seems to depend on that state. Any chance, that there is some instance of this class, which gets modified after it has been used as key in an LRU dictionary? This, too, would be consistent with your work-around. It should also fail with "plain" python dictionaries. Example:

```
d = {}
u = URL(...)
d[u] = "Hello"
u.set_file_name("bumm")
del d[u]
```

(haven't tested this, but would expect it to fail)

**Comment by andresriancho** [comment]
Yes, the mutable thing was what I suspected too. Hopefully my workaround is actually a fix :) I'll be able to know if after some time no user reports this bug again. For now we can close this issue, thanks!
